apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-devops-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: react-devops-deploy
  template:
    metadata:
      labels:
        name: react-devops-deploy
    spec:
      containers:
        - name: react-devops-deploy-container
          image: <dockerhub-username>/react-devops-deploy:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
